apiVersion: v1
kind: Service
metadata:
  name: app-image-service
  labels:
    name: app-image-service
    version: v1
spec:
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: app-image
    version: v1
  type: LoadBalancer

